workflows:
  build_and_test:
    jobs:
      - php81-build
      - php82-build
      - php83-build

version: 2.1

job-references:
  mysql_image: &mysql_image
    cimg/mysql:5.7

  setup_environment: &setup_environment
    name: "Setup Environment Variables"
    command: |
      echo "export PATH=$HOME/.composer/vendor/bin:$PATH" >> $BASH_ENV
      source /home/circleci/.bashrc

  install_dependencies: &install_dependencies
    name: "Install Dependencies"
    command: |
      sudo apt-get update && sudo apt-get install subversion git
      sudo -E docker-php-ext-install mysqli
      sudo apt-get update && sudo apt-get install mysql-client
      ssh-keyscan -p 443 ssh.github.com >> ~/.ssh/known_hosts

  php_job: &php_job
    environment:
      - WP_TESTS_DIR: "/tmp/wordpress-tests-lib"
      - WP_CORE_DIR: "/tmp/wordpress/"
    steps:
      - checkout
      - run: *setup_environment
      - run: *install_dependencies
      - run:
          name: "Run Tests"
          command: |
            git clone git@github.com:red-scale-dragon/app.git app
            cd app
            composer global require "phpunit/phpunit=11.4.4"
            composer update
            rm -rf $WP_TESTS_DIR $WP_CORE_DIR
            bash tests/bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest
            phpunit
            WP_MULTISITE=1 phpunit

jobs:
  php81-build:
    <<: *php_job
    docker:
      - image: cimg/php:8.1
      - image: *mysql_image

  php82-build:
    <<: *php_job
    docker:
      - image: cimg/php:8.2
      - image: *mysql_image

  php83-build:
    <<: *php_job
    docker:
      - image: cimg/php:8.2
      - image: *mysql_image
